# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'check_code_design.ui'
#
# Created: Wed Jun 22 13:33:32 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Lines_presentation(object):
    def setupUi(self, Lines_presentation):
        Lines_presentation.setObjectName(_fromUtf8("Lines_presentation"))
        Lines_presentation.resize(1292, 791)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("logo.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Lines_presentation.setWindowIcon(icon)
        self.horizontalLayoutWidget_26 = QtGui.QWidget(Lines_presentation)
        self.horizontalLayoutWidget_26.setGeometry(QtCore.QRect(10, 10, 1281, 710))
        self.horizontalLayoutWidget_26.setObjectName(_fromUtf8("horizontalLayoutWidget_26"))
        self.horizontalLayout_46 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_26)
        self.horizontalLayout_46.setMargin(0)
        self.horizontalLayout_46.setObjectName(_fromUtf8("horizontalLayout_46"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.line_counter_1 = QtGui.QLCDNumber(self.horizontalLayoutWidget_26)
        self.line_counter_1.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.line_counter_1.setFont(font)
        self.line_counter_1.setObjectName(_fromUtf8("line_counter_1"))
        self.horizontalLayout.addWidget(self.line_counter_1)
        self.displayLine_1 = QtGui.QPushButton(self.horizontalLayoutWidget_26)
        self.displayLine_1.setMinimumSize(QtCore.QSize(500, 0))
        self.displayLine_1.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.displayLine_1.setFont(font)
        self.displayLine_1.setText(_fromUtf8(""))
        self.displayLine_1.setObjectName(_fromUtf8("displayLine_1"))
        self.horizontalLayout.addWidget(self.displayLine_1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.line_counter_2 = QtGui.QLCDNumber(self.horizontalLayoutWidget_26)
        self.line_counter_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.line_counter_2.setObjectName(_fromUtf8("line_counter_2"))
        self.horizontalLayout_2.addWidget(self.line_counter_2)
        self.displayLine_2 = QtGui.QPushButton(self.horizontalLayoutWidget_26)
        self.displayLine_2.setMinimumSize(QtCore.QSize(500, 0))
        self.displayLine_2.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.displayLine_2.setFont(font)
        self.displayLine_2.setText(_fromUtf8(""))
        self.displayLine_2.setObjectName(_fromUtf8("displayLine_2"))
        self.horizontalLayout_2.addWidget(self.displayLine_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.line_counter_3 = QtGui.QLCDNumber(self.horizontalLayoutWidget_26)
        self.line_counter_3.setMaximumSize(QtCore.QSize(200, 16777215))
        self.line_counter_3.setObjectName(_fromUtf8("line_counter_3"))
        self.horizontalLayout_3.addWidget(self.line_counter_3)
        self.displayLine_3 = QtGui.QPushButton(self.horizontalLayoutWidget_26)
        self.displayLine_3.setMinimumSize(QtCore.QSize(500, 0))
        self.displayLine_3.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.displayLine_3.setFont(font)
        self.displayLine_3.setText(_fromUtf8(""))
        self.displayLine_3.setObjectName(_fromUtf8("displayLine_3"))
        self.horizontalLayout_3.addWidget(self.displayLine_3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.line_counter_4 = QtGui.QLCDNumber(self.horizontalLayoutWidget_26)
        self.line_counter_4.setMaximumSize(QtCore.QSize(200, 16777215))
        self.line_counter_4.setObjectName(_fromUtf8("line_counter_4"))
        self.horizontalLayout_4.addWidget(self.line_counter_4)
        self.displayLine_4 = QtGui.QPushButton(self.horizontalLayoutWidget_26)
        self.displayLine_4.setMinimumSize(QtCore.QSize(500, 0))
        self.displayLine_4.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.displayLine_4.setFont(font)
        self.displayLine_4.setText(_fromUtf8(""))
        self.displayLine_4.setObjectName(_fromUtf8("displayLine_4"))
        self.horizontalLayout_4.addWidget(self.displayLine_4)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.line_counter_5 = QtGui.QLCDNumber(self.horizontalLayoutWidget_26)
        self.line_counter_5.setMaximumSize(QtCore.QSize(200, 16777215))
        self.line_counter_5.setObjectName(_fromUtf8("line_counter_5"))
        self.horizontalLayout_9.addWidget(self.line_counter_5)
        self.displayLine_5 = QtGui.QPushButton(self.horizontalLayoutWidget_26)
        self.displayLine_5.setMinimumSize(QtCore.QSize(500, 0))
        self.displayLine_5.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.displayLine_5.setFont(font)
        self.displayLine_5.setText(_fromUtf8(""))
        self.displayLine_5.setObjectName(_fromUtf8("displayLine_5"))
        self.horizontalLayout_9.addWidget(self.displayLine_5)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.line_counter_6 = QtGui.QLCDNumber(self.horizontalLayoutWidget_26)
        self.line_counter_6.setMaximumSize(QtCore.QSize(200, 16777215))
        self.line_counter_6.setObjectName(_fromUtf8("line_counter_6"))
        self.horizontalLayout_10.addWidget(self.line_counter_6)
        self.displayLine_6 = QtGui.QPushButton(self.horizontalLayoutWidget_26)
        self.displayLine_6.setMinimumSize(QtCore.QSize(500, 0))
        self.displayLine_6.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.displayLine_6.setFont(font)
        self.displayLine_6.setText(_fromUtf8(""))
        self.displayLine_6.setObjectName(_fromUtf8("displayLine_6"))
        self.horizontalLayout_10.addWidget(self.displayLine_6)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.line_counter_7 = QtGui.QLCDNumber(self.horizontalLayoutWidget_26)
        self.line_counter_7.setMaximumSize(QtCore.QSize(200, 16777215))
        self.line_counter_7.setObjectName(_fromUtf8("line_counter_7"))
        self.horizontalLayout_6.addWidget(self.line_counter_7)
        self.displayLine_7 = QtGui.QPushButton(self.horizontalLayoutWidget_26)
        self.displayLine_7.setMinimumSize(QtCore.QSize(500, 0))
        self.displayLine_7.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.displayLine_7.setFont(font)
        self.displayLine_7.setText(_fromUtf8(""))
        self.displayLine_7.setObjectName(_fromUtf8("displayLine_7"))
        self.horizontalLayout_6.addWidget(self.displayLine_7)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.line_counter_8 = QtGui.QLCDNumber(self.horizontalLayoutWidget_26)
        self.line_counter_8.setMaximumSize(QtCore.QSize(200, 16777215))
        self.line_counter_8.setObjectName(_fromUtf8("line_counter_8"))
        self.horizontalLayout_8.addWidget(self.line_counter_8)
        self.displayLine_8 = QtGui.QPushButton(self.horizontalLayoutWidget_26)
        self.displayLine_8.setMinimumSize(QtCore.QSize(500, 0))
        self.displayLine_8.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.displayLine_8.setFont(font)
        self.displayLine_8.setText(_fromUtf8(""))
        self.displayLine_8.setObjectName(_fromUtf8("displayLine_8"))
        self.horizontalLayout_8.addWidget(self.displayLine_8)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.line_counter_9 = QtGui.QLCDNumber(self.horizontalLayoutWidget_26)
        self.line_counter_9.setMaximumSize(QtCore.QSize(200, 16777215))
        self.line_counter_9.setObjectName(_fromUtf8("line_counter_9"))
        self.horizontalLayout_7.addWidget(self.line_counter_9)
        self.displayLine_9 = QtGui.QPushButton(self.horizontalLayoutWidget_26)
        self.displayLine_9.setMinimumSize(QtCore.QSize(500, 0))
        self.displayLine_9.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.displayLine_9.setFont(font)
        self.displayLine_9.setText(_fromUtf8(""))
        self.displayLine_9.setObjectName(_fromUtf8("displayLine_9"))
        self.horizontalLayout_7.addWidget(self.displayLine_9)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.line_counter_10 = QtGui.QLCDNumber(self.horizontalLayoutWidget_26)
        self.line_counter_10.setMaximumSize(QtCore.QSize(200, 16777215))
        self.line_counter_10.setObjectName(_fromUtf8("line_counter_10"))
        self.horizontalLayout_5.addWidget(self.line_counter_10)
        self.displayLine_10 = QtGui.QPushButton(self.horizontalLayoutWidget_26)
        self.displayLine_10.setMinimumSize(QtCore.QSize(500, 0))
        self.displayLine_10.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.displayLine_10.setFont(font)
        self.displayLine_10.setText(_fromUtf8(""))
        self.displayLine_10.setObjectName(_fromUtf8("displayLine_10"))
        self.horizontalLayout_5.addWidget(self.displayLine_10)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.prevBtn = QtGui.QPushButton(self.horizontalLayoutWidget_26)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.prevBtn.setFont(font)
        self.prevBtn.setObjectName(_fromUtf8("prevBtn"))
        self.horizontalLayout_11.addWidget(self.prevBtn)
        self.nextBtn = QtGui.QPushButton(self.horizontalLayoutWidget_26)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.nextBtn.setFont(font)
        self.nextBtn.setObjectName(_fromUtf8("nextBtn"))
        self.horizontalLayout_11.addWidget(self.nextBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_47 = QtGui.QHBoxLayout()
        self.horizontalLayout_47.setObjectName(_fromUtf8("horizontalLayout_47"))
        self.saveBtn = QtGui.QPushButton(self.horizontalLayoutWidget_26)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.saveBtn.setFont(font)
        self.saveBtn.setObjectName(_fromUtf8("saveBtn"))
        self.horizontalLayout_47.addWidget(self.saveBtn)
        self.oneLineCheck = QtGui.QPushButton(self.horizontalLayoutWidget_26)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.oneLineCheck.setFont(font)
        self.oneLineCheck.setObjectName(_fromUtf8("oneLineCheck"))
        self.horizontalLayout_47.addWidget(self.oneLineCheck)
        self.verticalLayout.addLayout(self.horizontalLayout_47)
        self.horizontalLayout_46.addLayout(self.verticalLayout)
        self.line_10 = QtGui.QFrame(self.horizontalLayoutWidget_26)
        self.line_10.setFrameShape(QtGui.QFrame.VLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName(_fromUtf8("line_10"))
        self.horizontalLayout_46.addWidget(self.line_10)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label = QtGui.QLabel(self.horizontalLayoutWidget_26)
        self.label.setMinimumSize(QtCore.QSize(80, 0))
        self.label.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_12.addWidget(self.label)
        self.methodDisplay = QtGui.QLineEdit(self.horizontalLayoutWidget_26)
        self.methodDisplay.setMinimumSize(QtCore.QSize(600, 0))
        self.methodDisplay.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.methodDisplay.setFont(font)
        self.methodDisplay.setText(_fromUtf8(""))
        self.methodDisplay.setObjectName(_fromUtf8("methodDisplay"))
        self.horizontalLayout_12.addWidget(self.methodDisplay)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_2 = QtGui.QLabel(self.horizontalLayoutWidget_26)
        self.label_2.setMinimumSize(QtCore.QSize(80, 0))
        self.label_2.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_13.addWidget(self.label_2)
        self.addressDisplay = QtGui.QLineEdit(self.horizontalLayoutWidget_26)
        self.addressDisplay.setMinimumSize(QtCore.QSize(600, 0))
        self.addressDisplay.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addressDisplay.setFont(font)
        self.addressDisplay.setText(_fromUtf8(""))
        self.addressDisplay.setObjectName(_fromUtf8("addressDisplay"))
        self.horizontalLayout_13.addWidget(self.addressDisplay)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_3 = QtGui.QLabel(self.horizontalLayoutWidget_26)
        self.label_3.setMinimumSize(QtCore.QSize(80, 0))
        self.label_3.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_14.addWidget(self.label_3)
        self.titleDisplay = QtGui.QLineEdit(self.horizontalLayoutWidget_26)
        self.titleDisplay.setMinimumSize(QtCore.QSize(600, 0))
        self.titleDisplay.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.titleDisplay.setFont(font)
        self.titleDisplay.setText(_fromUtf8(""))
        self.titleDisplay.setObjectName(_fromUtf8("titleDisplay"))
        self.horizontalLayout_14.addWidget(self.titleDisplay)
        self.verticalLayout_2.addLayout(self.horizontalLayout_14)
        self.label_4 = QtGui.QLabel(self.horizontalLayoutWidget_26)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_2.addWidget(self.label_4)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.pName_1 = QtGui.QLineEdit(self.horizontalLayoutWidget_26)
        self.pName_1.setMinimumSize(QtCore.QSize(150, 0))
        self.pName_1.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pName_1.setFont(font)
        self.pName_1.setText(_fromUtf8(""))
        self.pName_1.setObjectName(_fromUtf8("pName_1"))
        self.horizontalLayout_23.addWidget(self.pName_1)
        self.label_11 = QtGui.QLabel(self.horizontalLayoutWidget_26)
        self.label_11.setMinimumSize(QtCore.QSize(10, 0))
        self.label_11.setMaximumSize(QtCore.QSize(17, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_23.addWidget(self.label_11)
        self.pValue_1 = QtGui.QLineEdit(self.horizontalLayoutWidget_26)
        self.pValue_1.setMinimumSize(QtCore.QSize(150, 0))
        self.pValue_1.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pValue_1.setFont(font)
        self.pValue_1.setObjectName(_fromUtf8("pValue_1"))
        self.horizontalLayout_23.addWidget(self.pValue_1)
        self.horizontalLayout_22.addLayout(self.horizontalLayout_23)
        self.line_5 = QtGui.QFrame(self.horizontalLayoutWidget_26)
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.horizontalLayout_22.addWidget(self.line_5)
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.pName_6 = QtGui.QLineEdit(self.horizontalLayoutWidget_26)
        self.pName_6.setMinimumSize(QtCore.QSize(150, 0))
        self.pName_6.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pName_6.setFont(font)
        self.pName_6.setText(_fromUtf8(""))
        self.pName_6.setObjectName(_fromUtf8("pName_6"))
        self.horizontalLayout_24.addWidget(self.pName_6)
        self.label_12 = QtGui.QLabel(self.horizontalLayoutWidget_26)
        self.label_12.setMinimumSize(QtCore.QSize(10, 0))
        self.label_12.setMaximumSize(QtCore.QSize(17, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_24.addWidget(self.label_12)
        self.pValue_6 = QtGui.QLineEdit(self.horizontalLayoutWidget_26)
        self.pValue_6.setMinimumSize(QtCore.QSize(150, 0))
        self.pValue_6.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pValue_6.setFont(font)
        self.pValue_6.setObjectName(_fromUtf8("pValue_6"))
        self.horizontalLayout_24.addWidget(self.pValue_6)
        self.horizontalLayout_22.addLayout(self.horizontalLayout_24)
        self.verticalLayout_2.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.pName_2 = QtGui.QLineEdit(self.horizontalLayoutWidget_26)
        self.pName_2.setMinimumSize(QtCore.QSize(150, 0))
        self.pName_2.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pName_2.setFont(font)
        self.pName_2.setText(_fromUtf8(""))
        self.pName_2.setObjectName(_fromUtf8("pName_2"))
        self.horizontalLayout_26.addWidget(self.pName_2)
        self.label_13 = QtGui.QLabel(self.horizontalLayoutWidget_26)
        self.label_13.setMinimumSize(QtCore.QSize(10, 0))
        self.label_13.setMaximumSize(QtCore.QSize(17, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_26.addWidget(self.label_13)
        self.pValue_2 = QtGui.QLineEdit(self.horizontalLayoutWidget_26)
        self.pValue_2.setMinimumSize(QtCore.QSize(150, 0))
        self.pValue_2.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pValue_2.setFont(font)
        self.pValue_2.setObjectName(_fromUtf8("pValue_2"))
        self.horizontalLayout_26.addWidget(self.pValue_2)
        self.horizontalLayout_25.addLayout(self.horizontalLayout_26)
        self.line_4 = QtGui.QFrame(self.horizontalLayoutWidget_26)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.horizontalLayout_25.addWidget(self.line_4)
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.pName_7 = QtGui.QLineEdit(self.horizontalLayoutWidget_26)
        self.pName_7.setMinimumSize(QtCore.QSize(150, 0))
        self.pName_7.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pName_7.setFont(font)
        self.pName_7.setText(_fromUtf8(""))
        self.pName_7.setObjectName(_fromUtf8("pName_7"))
        self.horizontalLayout_27.addWidget(self.pName_7)
        self.label_14 = QtGui.QLabel(self.horizontalLayoutWidget_26)
        self.label_14.setMinimumSize(QtCore.QSize(10, 0))
        self.label_14.setMaximumSize(QtCore.QSize(17, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_27.addWidget(self.label_14)
        self.pValue_7 = QtGui.QLineEdit(self.horizontalLayoutWidget_26)
        self.pValue_7.setMinimumSize(QtCore.QSize(150, 0))
        self.pValue_7.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pValue_7.setFont(font)
        self.pValue_7.setObjectName(_fromUtf8("pValue_7"))
        self.horizontalLayout_27.addWidget(self.pValue_7)
        self.horizontalLayout_25.addLayout(self.horizontalLayout_27)
        self.verticalLayout_2.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.horizontalLayout_29 = QtGui.QHBoxLayout()
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        self.pName_3 = QtGui.QLineEdit(self.horizontalLayoutWidget_26)
        self.pName_3.setMinimumSize(QtCore.QSize(150, 0))
        self.pName_3.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pName_3.setFont(font)
        self.pName_3.setText(_fromUtf8(""))
        self.pName_3.setObjectName(_fromUtf8("pName_3"))
        self.horizontalLayout_29.addWidget(self.pName_3)
        self.label_15 = QtGui.QLabel(self.horizontalLayoutWidget_26)
        self.label_15.setMinimumSize(QtCore.QSize(10, 0))
        self.label_15.setMaximumSize(QtCore.QSize(17, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_29.addWidget(self.label_15)
        self.pValue_3 = QtGui.QLineEdit(self.horizontalLayoutWidget_26)
        self.pValue_3.setMinimumSize(QtCore.QSize(150, 0))
        self.pValue_3.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pValue_3.setFont(font)
        self.pValue_3.setObjectName(_fromUtf8("pValue_3"))
        self.horizontalLayout_29.addWidget(self.pValue_3)
        self.horizontalLayout_28.addLayout(self.horizontalLayout_29)
        self.line_3 = QtGui.QFrame(self.horizontalLayoutWidget_26)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.horizontalLayout_28.addWidget(self.line_3)
        self.horizontalLayout_30 = QtGui.QHBoxLayout()
        self.horizontalLayout_30.setObjectName(_fromUtf8("horizontalLayout_30"))
        self.pName_8 = QtGui.QLineEdit(self.horizontalLayoutWidget_26)
        self.pName_8.setMinimumSize(QtCore.QSize(150, 0))
        self.pName_8.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pName_8.setFont(font)
        self.pName_8.setText(_fromUtf8(""))
        self.pName_8.setObjectName(_fromUtf8("pName_8"))
        self.horizontalLayout_30.addWidget(self.pName_8)
        self.label_16 = QtGui.QLabel(self.horizontalLayoutWidget_26)
        self.label_16.setMinimumSize(QtCore.QSize(10, 0))
        self.label_16.setMaximumSize(QtCore.QSize(17, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_30.addWidget(self.label_16)
        self.pValue_8 = QtGui.QLineEdit(self.horizontalLayoutWidget_26)
        self.pValue_8.setMinimumSize(QtCore.QSize(150, 0))
        self.pValue_8.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pValue_8.setFont(font)
        self.pValue_8.setObjectName(_fromUtf8("pValue_8"))
        self.horizontalLayout_30.addWidget(self.pValue_8)
        self.horizontalLayout_28.addLayout(self.horizontalLayout_30)
        self.verticalLayout_2.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_31 = QtGui.QHBoxLayout()
        self.horizontalLayout_31.setObjectName(_fromUtf8("horizontalLayout_31"))
        self.horizontalLayout_32 = QtGui.QHBoxLayout()
        self.horizontalLayout_32.setObjectName(_fromUtf8("horizontalLayout_32"))
        self.pName_4 = QtGui.QLineEdit(self.horizontalLayoutWidget_26)
        self.pName_4.setMinimumSize(QtCore.QSize(150, 0))
        self.pName_4.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pName_4.setFont(font)
        self.pName_4.setText(_fromUtf8(""))
        self.pName_4.setObjectName(_fromUtf8("pName_4"))
        self.horizontalLayout_32.addWidget(self.pName_4)
        self.label_17 = QtGui.QLabel(self.horizontalLayoutWidget_26)
        self.label_17.setMinimumSize(QtCore.QSize(10, 0))
        self.label_17.setMaximumSize(QtCore.QSize(17, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_32.addWidget(self.label_17)
        self.pValue_4 = QtGui.QLineEdit(self.horizontalLayoutWidget_26)
        self.pValue_4.setMinimumSize(QtCore.QSize(150, 0))
        self.pValue_4.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pValue_4.setFont(font)
        self.pValue_4.setObjectName(_fromUtf8("pValue_4"))
        self.horizontalLayout_32.addWidget(self.pValue_4)
        self.horizontalLayout_31.addLayout(self.horizontalLayout_32)
        self.line_2 = QtGui.QFrame(self.horizontalLayoutWidget_26)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.horizontalLayout_31.addWidget(self.line_2)
        self.horizontalLayout_33 = QtGui.QHBoxLayout()
        self.horizontalLayout_33.setObjectName(_fromUtf8("horizontalLayout_33"))
        self.pName_9 = QtGui.QLineEdit(self.horizontalLayoutWidget_26)
        self.pName_9.setMinimumSize(QtCore.QSize(150, 0))
        self.pName_9.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pName_9.setFont(font)
        self.pName_9.setText(_fromUtf8(""))
        self.pName_9.setObjectName(_fromUtf8("pName_9"))
        self.horizontalLayout_33.addWidget(self.pName_9)
        self.label_18 = QtGui.QLabel(self.horizontalLayoutWidget_26)
        self.label_18.setMinimumSize(QtCore.QSize(10, 0))
        self.label_18.setMaximumSize(QtCore.QSize(17, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_33.addWidget(self.label_18)
        self.pValue_9 = QtGui.QLineEdit(self.horizontalLayoutWidget_26)
        self.pValue_9.setMinimumSize(QtCore.QSize(150, 0))
        self.pValue_9.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pValue_9.setFont(font)
        self.pValue_9.setObjectName(_fromUtf8("pValue_9"))
        self.horizontalLayout_33.addWidget(self.pValue_9)
        self.horizontalLayout_31.addLayout(self.horizontalLayout_33)
        self.verticalLayout_2.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.pName_5 = QtGui.QLineEdit(self.horizontalLayoutWidget_26)
        self.pName_5.setMinimumSize(QtCore.QSize(150, 0))
        self.pName_5.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pName_5.setFont(font)
        self.pName_5.setText(_fromUtf8(""))
        self.pName_5.setObjectName(_fromUtf8("pName_5"))
        self.horizontalLayout_15.addWidget(self.pName_5)
        self.label_9 = QtGui.QLabel(self.horizontalLayoutWidget_26)
        self.label_9.setMinimumSize(QtCore.QSize(10, 0))
        self.label_9.setMaximumSize(QtCore.QSize(17, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_15.addWidget(self.label_9)
        self.pValue_5 = QtGui.QLineEdit(self.horizontalLayoutWidget_26)
        self.pValue_5.setMinimumSize(QtCore.QSize(150, 0))
        self.pValue_5.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pValue_5.setFont(font)
        self.pValue_5.setObjectName(_fromUtf8("pValue_5"))
        self.horizontalLayout_15.addWidget(self.pValue_5)
        self.horizontalLayout_21.addLayout(self.horizontalLayout_15)
        self.line = QtGui.QFrame(self.horizontalLayoutWidget_26)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_21.addWidget(self.line)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.pName_10 = QtGui.QLineEdit(self.horizontalLayoutWidget_26)
        self.pName_10.setMinimumSize(QtCore.QSize(150, 0))
        self.pName_10.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pName_10.setFont(font)
        self.pName_10.setText(_fromUtf8(""))
        self.pName_10.setObjectName(_fromUtf8("pName_10"))
        self.horizontalLayout_20.addWidget(self.pName_10)
        self.label_10 = QtGui.QLabel(self.horizontalLayoutWidget_26)
        self.label_10.setMinimumSize(QtCore.QSize(10, 0))
        self.label_10.setMaximumSize(QtCore.QSize(17, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_20.addWidget(self.label_10)
        self.pValue_10 = QtGui.QLineEdit(self.horizontalLayoutWidget_26)
        self.pValue_10.setMinimumSize(QtCore.QSize(150, 0))
        self.pValue_10.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pValue_10.setFont(font)
        self.pValue_10.setObjectName(_fromUtf8("pValue_10"))
        self.horizontalLayout_20.addWidget(self.pValue_10)
        self.horizontalLayout_21.addLayout(self.horizontalLayout_20)
        self.verticalLayout_2.addLayout(self.horizontalLayout_21)
        self.label_19 = QtGui.QLabel(self.horizontalLayoutWidget_26)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.verticalLayout_2.addWidget(self.label_19)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_43 = QtGui.QHBoxLayout()
        self.horizontalLayout_43.setObjectName(_fromUtf8("horizontalLayout_43"))
        self.horizontalLayout_44 = QtGui.QHBoxLayout()
        self.horizontalLayout_44.setObjectName(_fromUtf8("horizontalLayout_44"))
        self.label_28 = QtGui.QLabel(self.horizontalLayoutWidget_26)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.horizontalLayout_44.addWidget(self.label_28)
        self.label_29 = QtGui.QLabel(self.horizontalLayoutWidget_26)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.horizontalLayout_44.addWidget(self.label_29)
        self.horizontalLayout_43.addLayout(self.horizontalLayout_44)
        self.line_9 = QtGui.QFrame(self.horizontalLayoutWidget_26)
        self.line_9.setFrameShape(QtGui.QFrame.VLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.horizontalLayout_43.addWidget(self.line_9)
        self.horizontalLayout_45 = QtGui.QHBoxLayout()
        self.horizontalLayout_45.setObjectName(_fromUtf8("horizontalLayout_45"))
        self.label_30 = QtGui.QLabel(self.horizontalLayoutWidget_26)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.horizontalLayout_45.addWidget(self.label_30)
        self.label_31 = QtGui.QLabel(self.horizontalLayoutWidget_26)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.horizontalLayout_45.addWidget(self.label_31)
        self.horizontalLayout_43.addLayout(self.horizontalLayout_45)
        self.verticalLayout_4.addLayout(self.horizontalLayout_43)
        self.horizontalLayout_34 = QtGui.QHBoxLayout()
        self.horizontalLayout_34.setObjectName(_fromUtf8("horizontalLayout_34"))
        self.horizontalLayout_35 = QtGui.QHBoxLayout()
        self.horizontalLayout_35.setObjectName(_fromUtf8("horizontalLayout_35"))
        self.cName_1 = QtGui.QLineEdit(self.horizontalLayoutWidget_26)
        self.cName_1.setMinimumSize(QtCore.QSize(150, 0))
        self.cName_1.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cName_1.setFont(font)
        self.cName_1.setText(_fromUtf8(""))
        self.cName_1.setObjectName(_fromUtf8("cName_1"))
        self.horizontalLayout_35.addWidget(self.cName_1)
        self.label_20 = QtGui.QLabel(self.horizontalLayoutWidget_26)
        self.label_20.setMinimumSize(QtCore.QSize(10, 0))
        self.label_20.setMaximumSize(QtCore.QSize(17, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_35.addWidget(self.label_20)
        self.cValue_1 = QtGui.QLineEdit(self.horizontalLayoutWidget_26)
        self.cValue_1.setMinimumSize(QtCore.QSize(150, 0))
        self.cValue_1.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cValue_1.setFont(font)
        self.cValue_1.setObjectName(_fromUtf8("cValue_1"))
        self.horizontalLayout_35.addWidget(self.cValue_1)
        self.horizontalLayout_34.addLayout(self.horizontalLayout_35)
        self.line_6 = QtGui.QFrame(self.horizontalLayoutWidget_26)
        self.line_6.setFrameShape(QtGui.QFrame.VLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.horizontalLayout_34.addWidget(self.line_6)
        self.horizontalLayout_36 = QtGui.QHBoxLayout()
        self.horizontalLayout_36.setObjectName(_fromUtf8("horizontalLayout_36"))
        self.cName_4 = QtGui.QLineEdit(self.horizontalLayoutWidget_26)
        self.cName_4.setMinimumSize(QtCore.QSize(150, 0))
        self.cName_4.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cName_4.setFont(font)
        self.cName_4.setText(_fromUtf8(""))
        self.cName_4.setObjectName(_fromUtf8("cName_4"))
        self.horizontalLayout_36.addWidget(self.cName_4)
        self.label_21 = QtGui.QLabel(self.horizontalLayoutWidget_26)
        self.label_21.setMinimumSize(QtCore.QSize(10, 0))
        self.label_21.setMaximumSize(QtCore.QSize(17, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_36.addWidget(self.label_21)
        self.cValue_4 = QtGui.QLineEdit(self.horizontalLayoutWidget_26)
        self.cValue_4.setMinimumSize(QtCore.QSize(150, 0))
        self.cValue_4.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cValue_4.setFont(font)
        self.cValue_4.setObjectName(_fromUtf8("cValue_4"))
        self.horizontalLayout_36.addWidget(self.cValue_4)
        self.horizontalLayout_34.addLayout(self.horizontalLayout_36)
        self.verticalLayout_4.addLayout(self.horizontalLayout_34)
        self.horizontalLayout_40 = QtGui.QHBoxLayout()
        self.horizontalLayout_40.setObjectName(_fromUtf8("horizontalLayout_40"))
        self.horizontalLayout_41 = QtGui.QHBoxLayout()
        self.horizontalLayout_41.setObjectName(_fromUtf8("horizontalLayout_41"))
        self.cName_2 = QtGui.QLineEdit(self.horizontalLayoutWidget_26)
        self.cName_2.setMinimumSize(QtCore.QSize(150, 0))
        self.cName_2.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cName_2.setFont(font)
        self.cName_2.setText(_fromUtf8(""))
        self.cName_2.setObjectName(_fromUtf8("cName_2"))
        self.horizontalLayout_41.addWidget(self.cName_2)
        self.label_24 = QtGui.QLabel(self.horizontalLayoutWidget_26)
        self.label_24.setMinimumSize(QtCore.QSize(10, 0))
        self.label_24.setMaximumSize(QtCore.QSize(17, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_41.addWidget(self.label_24)
        self.cValue_2 = QtGui.QLineEdit(self.horizontalLayoutWidget_26)
        self.cValue_2.setMinimumSize(QtCore.QSize(150, 0))
        self.cValue_2.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cValue_2.setFont(font)
        self.cValue_2.setObjectName(_fromUtf8("cValue_2"))
        self.horizontalLayout_41.addWidget(self.cValue_2)
        self.horizontalLayout_40.addLayout(self.horizontalLayout_41)
        self.line_8 = QtGui.QFrame(self.horizontalLayoutWidget_26)
        self.line_8.setFrameShape(QtGui.QFrame.VLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.horizontalLayout_40.addWidget(self.line_8)
        self.horizontalLayout_42 = QtGui.QHBoxLayout()
        self.horizontalLayout_42.setObjectName(_fromUtf8("horizontalLayout_42"))
        self.cName_5 = QtGui.QLineEdit(self.horizontalLayoutWidget_26)
        self.cName_5.setMinimumSize(QtCore.QSize(150, 0))
        self.cName_5.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cName_5.setFont(font)
        self.cName_5.setText(_fromUtf8(""))
        self.cName_5.setObjectName(_fromUtf8("cName_5"))
        self.horizontalLayout_42.addWidget(self.cName_5)
        self.label_25 = QtGui.QLabel(self.horizontalLayoutWidget_26)
        self.label_25.setMinimumSize(QtCore.QSize(10, 0))
        self.label_25.setMaximumSize(QtCore.QSize(17, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout_42.addWidget(self.label_25)
        self.cValue_5 = QtGui.QLineEdit(self.horizontalLayoutWidget_26)
        self.cValue_5.setMinimumSize(QtCore.QSize(150, 0))
        self.cValue_5.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cValue_5.setFont(font)
        self.cValue_5.setObjectName(_fromUtf8("cValue_5"))
        self.horizontalLayout_42.addWidget(self.cValue_5)
        self.horizontalLayout_40.addLayout(self.horizontalLayout_42)
        self.verticalLayout_4.addLayout(self.horizontalLayout_40)
        self.horizontalLayout_37 = QtGui.QHBoxLayout()
        self.horizontalLayout_37.setObjectName(_fromUtf8("horizontalLayout_37"))
        self.horizontalLayout_38 = QtGui.QHBoxLayout()
        self.horizontalLayout_38.setObjectName(_fromUtf8("horizontalLayout_38"))
        self.cName_3 = QtGui.QLineEdit(self.horizontalLayoutWidget_26)
        self.cName_3.setMinimumSize(QtCore.QSize(150, 0))
        self.cName_3.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cName_3.setFont(font)
        self.cName_3.setText(_fromUtf8(""))
        self.cName_3.setObjectName(_fromUtf8("cName_3"))
        self.horizontalLayout_38.addWidget(self.cName_3)
        self.label_22 = QtGui.QLabel(self.horizontalLayoutWidget_26)
        self.label_22.setMinimumSize(QtCore.QSize(10, 0))
        self.label_22.setMaximumSize(QtCore.QSize(17, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_38.addWidget(self.label_22)
        self.cValue_3 = QtGui.QLineEdit(self.horizontalLayoutWidget_26)
        self.cValue_3.setMinimumSize(QtCore.QSize(150, 0))
        self.cValue_3.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cValue_3.setFont(font)
        self.cValue_3.setObjectName(_fromUtf8("cValue_3"))
        self.horizontalLayout_38.addWidget(self.cValue_3)
        self.horizontalLayout_37.addLayout(self.horizontalLayout_38)
        self.line_7 = QtGui.QFrame(self.horizontalLayoutWidget_26)
        self.line_7.setFrameShape(QtGui.QFrame.VLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.horizontalLayout_37.addWidget(self.line_7)
        self.horizontalLayout_39 = QtGui.QHBoxLayout()
        self.horizontalLayout_39.setObjectName(_fromUtf8("horizontalLayout_39"))
        self.cName_6 = QtGui.QLineEdit(self.horizontalLayoutWidget_26)
        self.cName_6.setMinimumSize(QtCore.QSize(150, 0))
        self.cName_6.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cName_6.setFont(font)
        self.cName_6.setText(_fromUtf8(""))
        self.cName_6.setObjectName(_fromUtf8("cName_6"))
        self.horizontalLayout_39.addWidget(self.cName_6)
        self.label_23 = QtGui.QLabel(self.horizontalLayoutWidget_26)
        self.label_23.setMinimumSize(QtCore.QSize(10, 0))
        self.label_23.setMaximumSize(QtCore.QSize(17, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_39.addWidget(self.label_23)
        self.cValue_6 = QtGui.QLineEdit(self.horizontalLayoutWidget_26)
        self.cValue_6.setMinimumSize(QtCore.QSize(150, 0))
        self.cValue_6.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cValue_6.setFont(font)
        self.cValue_6.setObjectName(_fromUtf8("cValue_6"))
        self.horizontalLayout_39.addWidget(self.cValue_6)
        self.horizontalLayout_37.addLayout(self.horizontalLayout_39)
        self.verticalLayout_4.addLayout(self.horizontalLayout_37)
        self.verticalLayout_2.addLayout(self.verticalLayout_4)
        self.label_26 = QtGui.QLabel(self.horizontalLayoutWidget_26)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.verticalLayout_2.addWidget(self.label_26)
        self.find_1 = QtGui.QLineEdit(self.horizontalLayoutWidget_26)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.find_1.setFont(font)
        self.find_1.setText(_fromUtf8(""))
        self.find_1.setObjectName(_fromUtf8("find_1"))
        self.verticalLayout_2.addWidget(self.find_1)
        self.find_2 = QtGui.QLineEdit(self.horizontalLayoutWidget_26)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.find_2.setFont(font)
        self.find_2.setText(_fromUtf8(""))
        self.find_2.setObjectName(_fromUtf8("find_2"))
        self.verticalLayout_2.addWidget(self.find_2)
        self.find_3 = QtGui.QLineEdit(self.horizontalLayoutWidget_26)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.find_3.setFont(font)
        self.find_3.setText(_fromUtf8(""))
        self.find_3.setObjectName(_fromUtf8("find_3"))
        self.verticalLayout_2.addWidget(self.find_3)
        self.horizontalLayout_46.addLayout(self.verticalLayout_2)

        self.retranslateUi(Lines_presentation)
        QtCore.QMetaObject.connectSlotsByName(Lines_presentation)

    def retranslateUi(self, Lines_presentation):
        Lines_presentation.setWindowTitle(_translate("Lines_presentation", "API Test - Code Check", None))
        self.prevBtn.setText(_translate("Lines_presentation", "Prev", None))
        self.nextBtn.setText(_translate("Lines_presentation", "Next", None))
        self.saveBtn.setText(_translate("Lines_presentation", "Save Line", None))
        self.oneLineCheck.setText(_translate("Lines_presentation", "Check only the selected line", None))
        self.label.setText(_translate("Lines_presentation", "Method:", None))
        self.label_2.setText(_translate("Lines_presentation", "Address:", None))
        self.label_3.setText(_translate("Lines_presentation", "Title:", None))
        self.label_4.setText(_translate("Lines_presentation", "                                                      Params:", None))
        self.label_11.setText(_translate("Lines_presentation", "=>", None))
        self.label_12.setText(_translate("Lines_presentation", "=>", None))
        self.label_13.setText(_translate("Lines_presentation", "=>", None))
        self.label_14.setText(_translate("Lines_presentation", "=>", None))
        self.label_15.setText(_translate("Lines_presentation", "=>", None))
        self.label_16.setText(_translate("Lines_presentation", "=>", None))
        self.label_17.setText(_translate("Lines_presentation", "=>", None))
        self.label_18.setText(_translate("Lines_presentation", "=>", None))
        self.label_9.setText(_translate("Lines_presentation", "=>", None))
        self.label_10.setText(_translate("Lines_presentation", "=>", None))
        self.label_19.setText(_translate("Lines_presentation", "                                                       Check:", None))
        self.label_28.setText(_translate("Lines_presentation", "          Name", None))
        self.label_29.setText(_translate("Lines_presentation", "            Value", None))
        self.label_30.setText(_translate("Lines_presentation", "          Name", None))
        self.label_31.setText(_translate("Lines_presentation", "            Value", None))
        self.label_20.setText(_translate("Lines_presentation", "=>", None))
        self.label_21.setText(_translate("Lines_presentation", "=>", None))
        self.label_24.setText(_translate("Lines_presentation", "=>", None))
        self.label_25.setText(_translate("Lines_presentation", "=>", None))
        self.label_22.setText(_translate("Lines_presentation", "=>", None))
        self.label_23.setText(_translate("Lines_presentation", "=>", None))
        self.label_26.setText(_translate("Lines_presentation", "                                                          Find:", None))

