# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_design.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(915, 640)
        Dialog.setMinimumSize(QtCore.QSize(915, 640))
        Dialog.setMaximumSize(QtCore.QSize(915, 640))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("logo.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet(_fromUtf8("background: rgb(128,128, 128)"))
        self.horizontalLayoutWidget_2 = QtGui.QWidget(Dialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 0, 901, 638))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.tableWidget = QtGui.QTableWidget(self.horizontalLayoutWidget_2)
        self.tableWidget.setMinimumSize(QtCore.QSize(500, 635))
        self.tableWidget.setMaximumSize(QtCore.QSize(500, 635))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet(_fromUtf8("background:rgb(204,204,204);\n"
"border: 1px solid black;\n"
""))
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.horizontalLayout_5.addWidget(self.tableWidget)
        self.line = QtGui.QFrame(self.horizontalLayoutWidget_2)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_5.addWidget(self.line)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label.setMinimumSize(QtCore.QSize(60, 30))
        self.label.setMaximumSize(QtCore.QSize(60, 30))
        self.label.setStyleSheet(_fromUtf8("background:rgb(204,204,204);\n"
"border-radius: 5px;"))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtGui.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit.setMinimumSize(QtCore.QSize(305, 30))
        self.lineEdit.setMaximumSize(QtCore.QSize(305, 30))
        self.lineEdit.setStyleSheet(_fromUtf8("background:rgb(204,204,204);\n"
"border: 2px solid black;\n"
"border-radius: 5px;"))
        self.lineEdit.setText(_fromUtf8(""))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_2.setMinimumSize(QtCore.QSize(60, 30))
        self.label_2.setMaximumSize(QtCore.QSize(60, 30))
        self.label_2.setStyleSheet(_fromUtf8("background:rgb(204,204,204);\n"
"border-radius: 5px;"))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_2 = QtGui.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(305, 30))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(305, 30))
        self.lineEdit_2.setStyleSheet(_fromUtf8("background:rgb(204,204,204);\n"
"border: 2px solid black;\n"
"border-radius: 5px;"))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_3.setMinimumSize(QtCore.QSize(60, 30))
        self.label_3.setMaximumSize(QtCore.QSize(60, 30))
        self.label_3.setStyleSheet(_fromUtf8("background:rgb(204,204,204);\n"
"border-radius: 5px;"))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lineEdit_3 = QtGui.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(305, 30))
        self.lineEdit_3.setMaximumSize(QtCore.QSize(305, 30))
        self.lineEdit_3.setStyleSheet(_fromUtf8("background:rgb(204,204,204);\n"
"border: 2px solid black;\n"
"border-radius: 5px;"))
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.horizontalLayout_3.addWidget(self.lineEdit_3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_4 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_4.setMinimumSize(QtCore.QSize(90, 30))
        self.label_4.setMaximumSize(QtCore.QSize(90, 30))
        self.label_4.setStyleSheet(_fromUtf8("background:rgb(204,204,204);\n"
"border-radius: 5px;"))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_5.addWidget(self.label_4)
        self.label_5 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_5.setMinimumSize(QtCore.QSize(90, 30))
        self.label_5.setMaximumSize(QtCore.QSize(90, 30))
        self.label_5.setStyleSheet(_fromUtf8("background:rgb(204,204,204);\n"
"border-radius: 5px;"))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_5.addWidget(self.label_5)
        self.label_6 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_6.setMinimumSize(QtCore.QSize(90, 30))
        self.label_6.setMaximumSize(QtCore.QSize(90, 30))
        self.label_6.setStyleSheet(_fromUtf8("background:rgb(204,204,204);\n"
"border-radius: 5px;"))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_5.addWidget(self.label_6)
        self.horizontalLayout_6.addLayout(self.verticalLayout_5)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.reg_proj = QtGui.QLineEdit(self.horizontalLayoutWidget_2)
        self.reg_proj.setMinimumSize(QtCore.QSize(85, 30))
        self.reg_proj.setMaximumSize(QtCore.QSize(85, 30))
        self.reg_proj.setStyleSheet(_fromUtf8("background:rgb(204,204,204);\n"
"border: 2px solid black;\n"
"border-radius: 5px;"))
        self.reg_proj.setObjectName(_fromUtf8("reg_proj"))
        self.verticalLayout_4.addWidget(self.reg_proj)
        self.expert_proj = QtGui.QLineEdit(self.horizontalLayoutWidget_2)
        self.expert_proj.setMinimumSize(QtCore.QSize(85, 30))
        self.expert_proj.setMaximumSize(QtCore.QSize(85, 30))
        self.expert_proj.setStyleSheet(_fromUtf8("background:rgb(204,204,204);\n"
"border: 2px solid black;\n"
"border-radius: 5px;"))
        self.expert_proj.setObjectName(_fromUtf8("expert_proj"))
        self.verticalLayout_4.addWidget(self.expert_proj)
        self.proof_proj = QtGui.QLineEdit(self.horizontalLayoutWidget_2)
        self.proof_proj.setMinimumSize(QtCore.QSize(85, 30))
        self.proof_proj.setMaximumSize(QtCore.QSize(85, 30))
        self.proof_proj.setStyleSheet(_fromUtf8("background:rgb(204,204,204);\n"
"border: 2px solid black;\n"
"border-radius: 5px;"))
        self.proof_proj.setObjectName(_fromUtf8("proof_proj"))
        self.verticalLayout_4.addWidget(self.proof_proj)
        self.horizontalLayout_6.addLayout(self.verticalLayout_4)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_8 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_8.setMinimumSize(QtCore.QSize(90, 30))
        self.label_8.setMaximumSize(QtCore.QSize(90, 30))
        self.label_8.setStyleSheet(_fromUtf8("background:rgb(204,204,204);\n"
"border-radius: 5px;"))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_7.addWidget(self.label_8)
        self.label_7 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_7.setMinimumSize(QtCore.QSize(90, 30))
        self.label_7.setMaximumSize(QtCore.QSize(90, 30))
        self.label_7.setStyleSheet(_fromUtf8("background:rgb(204,204,204);\n"
"border-radius: 5px;"))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_7.addWidget(self.label_7)
        spacerItem = QtGui.QSpacerItem(20, 30, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_7.addItem(spacerItem)
        self.horizontalLayout_12.addLayout(self.verticalLayout_7)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.combo_proj = QtGui.QLineEdit(self.horizontalLayoutWidget_2)
        self.combo_proj.setMinimumSize(QtCore.QSize(85, 30))
        self.combo_proj.setMaximumSize(QtCore.QSize(85, 30))
        self.combo_proj.setStyleSheet(_fromUtf8("background:rgb(204,204,204);\n"
"border: 2px solid black;\n"
"border-radius: 5px;"))
        self.combo_proj.setObjectName(_fromUtf8("combo_proj"))
        self.verticalLayout_6.addWidget(self.combo_proj)
        self.transcript_proj = QtGui.QLineEdit(self.horizontalLayoutWidget_2)
        self.transcript_proj.setMinimumSize(QtCore.QSize(85, 30))
        self.transcript_proj.setMaximumSize(QtCore.QSize(85, 30))
        self.transcript_proj.setStyleSheet(_fromUtf8("background:rgb(204,204,204);\n"
"border: 2px solid black;\n"
"border-radius: 5px;"))
        self.transcript_proj.setObjectName(_fromUtf8("transcript_proj"))
        self.verticalLayout_6.addWidget(self.transcript_proj)
        spacerItem1 = QtGui.QSpacerItem(20, 30, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_6.addItem(spacerItem1)
        self.horizontalLayout_12.addLayout(self.verticalLayout_6)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_12)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.loadTxtBtn = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadTxtBtn.sizePolicy().hasHeightForWidth())
        self.loadTxtBtn.setSizePolicy(sizePolicy)
        self.loadTxtBtn.setMinimumSize(QtCore.QSize(144, 30))
        self.loadTxtBtn.setMaximumSize(QtCore.QSize(144, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.loadTxtBtn.setFont(font)
        self.loadTxtBtn.setStyleSheet(_fromUtf8("background:rgb(80,80,80);\n"
"color: rgb(204,204,204);\n"
""))
        self.loadTxtBtn.setObjectName(_fromUtf8("loadTxtBtn"))
        self.horizontalLayout_11.addWidget(self.loadTxtBtn)
        self.delTextFile = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.delTextFile.setMinimumSize(QtCore.QSize(30, 30))
        self.delTextFile.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.delTextFile.setFont(font)
        self.delTextFile.setStyleSheet(_fromUtf8("background:rgb(77, 0, 0);color: rgb(204,204,204);"))
        self.delTextFile.setObjectName(_fromUtf8("delTextFile"))
        self.horizontalLayout_11.addWidget(self.delTextFile)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.txtFilesList = QtGui.QListWidget(self.horizontalLayoutWidget_2)
        self.txtFilesList.setEnabled(True)
        self.txtFilesList.setMinimumSize(QtCore.QSize(180, 100))
        self.txtFilesList.setMaximumSize(QtCore.QSize(180, 100))
        self.txtFilesList.setStyleSheet(_fromUtf8("background:rgb(204,204,204);\n"
"border: 2px solid black;\n"
"border-radius: 5px;"))
        self.txtFilesList.setObjectName(_fromUtf8("txtFilesList"))
        self.verticalLayout_2.addWidget(self.txtFilesList)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setSpacing(3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.loadFileBtn = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadFileBtn.sizePolicy().hasHeightForWidth())
        self.loadFileBtn.setSizePolicy(sizePolicy)
        self.loadFileBtn.setMinimumSize(QtCore.QSize(144, 30))
        self.loadFileBtn.setMaximumSize(QtCore.QSize(144, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.loadFileBtn.setFont(font)
        self.loadFileBtn.setStyleSheet(_fromUtf8("background:rgb(80,80,80);\n"
"color: rgb(204,204,204);"))
        self.loadFileBtn.setObjectName(_fromUtf8("loadFileBtn"))
        self.horizontalLayout_13.addWidget(self.loadFileBtn)
        self.delFile = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.delFile.setMinimumSize(QtCore.QSize(30, 30))
        self.delFile.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.delFile.setFont(font)
        self.delFile.setAutoFillBackground(False)
        self.delFile.setStyleSheet(_fromUtf8("background:rgb(77, 0, 0);color: rgb(204,204,204);"))
        self.delFile.setObjectName(_fromUtf8("delFile"))
        self.horizontalLayout_13.addWidget(self.delFile)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.testFilesList = QtGui.QListWidget(self.horizontalLayoutWidget_2)
        self.testFilesList.setMinimumSize(QtCore.QSize(180, 100))
        self.testFilesList.setMaximumSize(QtCore.QSize(180, 100))
        self.testFilesList.setStyleSheet(_fromUtf8("background:rgb(204,204,204);\n"
"border: 2px solid black;\n"
"border-radius: 5px;"))
        self.testFilesList.setObjectName(_fromUtf8("testFilesList"))
        self.verticalLayout_3.addWidget(self.testFilesList)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.checkDisplay = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.checkDisplay.setMinimumSize(QtCore.QSize(180, 60))
        self.checkDisplay.setMaximumSize(QtCore.QSize(180, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkDisplay.setFont(font)
        self.checkDisplay.setStyleSheet(_fromUtf8("background:rgb(80,80,80);\n"
"color: rgb(204,204,204);"))
        self.checkDisplay.setObjectName(_fromUtf8("checkDisplay"))
        self.horizontalLayout_8.addWidget(self.checkDisplay)
        self.fileLoad = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.fileLoad.setMinimumSize(QtCore.QSize(180, 60))
        self.fileLoad.setMaximumSize(QtCore.QSize(180, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.fileLoad.setFont(font)
        self.fileLoad.setStyleSheet(_fromUtf8("background:rgb(80,80,80);\n"
"color: rgb(204,204,204);"))
        self.fileLoad.setObjectName(_fromUtf8("fileLoad"))
        self.horizontalLayout_8.addWidget(self.fileLoad)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.startBtn = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(97)
        sizePolicy.setVerticalStretch(60)
        sizePolicy.setHeightForWidth(self.startBtn.sizePolicy().hasHeightForWidth())
        self.startBtn.setSizePolicy(sizePolicy)
        self.startBtn.setMinimumSize(QtCore.QSize(180, 60))
        self.startBtn.setMaximumSize(QtCore.QSize(180, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.startBtn.setFont(font)
        self.startBtn.setStyleSheet(_fromUtf8("background:rgb(0, 51, 0);\n"
"color: rgb(204,204,204);"))
        self.startBtn.setIconSize(QtCore.QSize(24, 24))
        self.startBtn.setObjectName(_fromUtf8("startBtn"))
        self.horizontalLayout_9.addWidget(self.startBtn)
        self.stopBtn = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.stopBtn.setMinimumSize(QtCore.QSize(180, 60))
        self.stopBtn.setMaximumSize(QtCore.QSize(180, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.stopBtn.setFont(font)
        self.stopBtn.setStyleSheet(_fromUtf8("background:rgb(77, 0, 0);\n"
"color: rgb(204,204,204);"))
        self.stopBtn.setObjectName(_fromUtf8("stopBtn"))
        self.horizontalLayout_9.addWidget(self.stopBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.reportBtn = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.reportBtn.setMinimumSize(QtCore.QSize(180, 60))
        self.reportBtn.setMaximumSize(QtCore.QSize(180, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.reportBtn.setFont(font)
        self.reportBtn.setStyleSheet(_fromUtf8("background:rgb(80,80,80);\n"
"color: rgb(204,204,204);"))
        self.reportBtn.setObjectName(_fromUtf8("reportBtn"))
        self.horizontalLayout_10.addWidget(self.reportBtn)
        self.pushButton_2 = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_2.setMinimumSize(QtCore.QSize(180, 60))
        self.pushButton_2.setMaximumSize(QtCore.QSize(180, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet(_fromUtf8("background:rgb(80,80,80);\n"
"color: rgb(204,204,204);"))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout_10.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.progressBar = QtGui.QProgressBar(self.horizontalLayoutWidget_2)
        self.progressBar.setMinimumSize(QtCore.QSize(375, 40))
        self.progressBar.setMaximumSize(QtCore.QSize(375, 40))
        self.progressBar.setStyleSheet(_fromUtf8("background:rgb(204,204,204);"))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.verticalLayout.addWidget(self.progressBar)
        self.horizontalLayout_5.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "API Test", None))
        self.label.setText(_translate("Dialog", " Secret Key", None))
        self.label_2.setText(_translate("Dialog", " Public Key ", None))
        self.label_3.setText(_translate("Dialog", " http:     ", None))
        self.label_4.setText(_translate("Dialog", " Regular Project", None))
        self.label_5.setText(_translate("Dialog", " Expert Project", None))
        self.label_6.setText(_translate("Dialog", " Proofreading", None))
        self.label_8.setText(_translate("Dialog", " Combo Project", None))
        self.label_7.setText(_translate("Dialog", " Transcription", None))
        self.loadTxtBtn.setText(_translate("Dialog", "Load Text Files", None))
        self.delTextFile.setText(_translate("Dialog", "X", None))
        self.loadFileBtn.setText(_translate("Dialog", "Load Files", None))
        self.delFile.setText(_translate("Dialog", "X", None))
        self.checkDisplay.setText(_translate("Dialog", "Whole check display", None))
        self.fileLoad.setText(_translate("Dialog", "Load Test File", None))
        self.startBtn.setText(_translate("Dialog", "Start Test", None))
        self.stopBtn.setText(_translate("Dialog", "Stop Test", None))
        self.reportBtn.setText(_translate("Dialog", "See Report", None))
        self.pushButton_2.setText(_translate("Dialog", "Quit", None))

