# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_design.ui'
#
# Created: Thu Jun 16 17:50:55 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(1089, 630)
        self.gridLayoutWidget = QtGui.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 729, 613))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.gridLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_2 = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lineEdit_3 = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.horizontalLayout_3.addWidget(self.lineEdit_3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 3, 1, 1)
        self.startBtn = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(97)
        sizePolicy.setVerticalStretch(60)
        sizePolicy.setHeightForWidth(self.startBtn.sizePolicy().hasHeightForWidth())
        self.startBtn.setSizePolicy(sizePolicy)
        self.startBtn.setMinimumSize(QtCore.QSize(97, 60))
        self.startBtn.setIconSize(QtCore.QSize(24, 24))
        self.startBtn.setObjectName(_fromUtf8("startBtn"))
        self.gridLayout_2.addWidget(self.startBtn, 0, 0, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(97, 60))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout_2.addWidget(self.pushButton_2, 0, 2, 1, 1)
        self.fileLoad = QtGui.QPushButton(self.gridLayoutWidget)
        self.fileLoad.setMinimumSize(QtCore.QSize(97, 60))
        self.fileLoad.setObjectName(_fromUtf8("fileLoad"))
        self.gridLayout_2.addWidget(self.fileLoad, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.tableWidget = QtGui.QTableWidget(self.gridLayoutWidget)
        self.tableWidget.setMinimumSize(QtCore.QSize(0, 500))
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget, 1, 0, 1, 1)
        self.horizontalLayoutWidget = QtGui.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(760, 10, 321, 311))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.loadTxtBtn = QtGui.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadTxtBtn.sizePolicy().hasHeightForWidth())
        self.loadTxtBtn.setSizePolicy(sizePolicy)
        self.loadTxtBtn.setMinimumSize(QtCore.QSize(97, 60))
        self.loadTxtBtn.setMaximumSize(QtCore.QSize(97, 60))
        self.loadTxtBtn.setObjectName(_fromUtf8("loadTxtBtn"))
        self.horizontalLayout_4.addWidget(self.loadTxtBtn)
        spacerItem = QtGui.QSpacerItem(0, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.loadFileBtn = QtGui.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadFileBtn.sizePolicy().hasHeightForWidth())
        self.loadFileBtn.setSizePolicy(sizePolicy)
        self.loadFileBtn.setMinimumSize(QtCore.QSize(97, 60))
        self.loadFileBtn.setMaximumSize(QtCore.QSize(97, 60))
        self.loadFileBtn.setObjectName(_fromUtf8("loadFileBtn"))
        self.horizontalLayout_4.addWidget(self.loadFileBtn)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.txtFilesList = QtGui.QListWidget(self.horizontalLayoutWidget)
        self.txtFilesList.setEnabled(True)
        self.txtFilesList.setMinimumSize(QtCore.QSize(150, 0))
        self.txtFilesList.setMaximumSize(QtCore.QSize(150, 16777215))
        self.txtFilesList.setObjectName(_fromUtf8("txtFilesList"))
        self.horizontalLayout_5.addWidget(self.txtFilesList)
        self.testFilesList = QtGui.QListWidget(self.horizontalLayoutWidget)
        self.testFilesList.setMaximumSize(QtCore.QSize(150, 16777215))
        self.testFilesList.setObjectName(_fromUtf8("testFilesList"))
        self.horizontalLayout_5.addWidget(self.testFilesList)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6.addLayout(self.verticalLayout_3)
        self.line = QtGui.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(740, 10, 16, 571))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.progressBar = QtGui.QProgressBar(Dialog)
        self.progressBar.setGeometry(QtCore.QRect(760, 560, 317, 21))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.verticalLayoutWidget = QtGui.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(760, 330, 160, 171))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_4 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_4.setMinimumSize(QtCore.QSize(80, 0))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_7.addWidget(self.label_4)
        self.reg_proj = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.reg_proj.setObjectName(_fromUtf8("reg_proj"))
        self.horizontalLayout_7.addWidget(self.reg_proj)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_5 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_5.setMinimumSize(QtCore.QSize(80, 0))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_8.addWidget(self.label_5)
        self.expert_proj = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.expert_proj.setObjectName(_fromUtf8("expert_proj"))
        self.horizontalLayout_8.addWidget(self.expert_proj)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_6 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_6.setMinimumSize(QtCore.QSize(80, 0))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_9.addWidget(self.label_6)
        self.proof_proj = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.proof_proj.setObjectName(_fromUtf8("proof_proj"))
        self.horizontalLayout_9.addWidget(self.proof_proj)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_7 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_7.setMinimumSize(QtCore.QSize(80, 0))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_10.addWidget(self.label_7)
        self.transcript_proj = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.transcript_proj.setObjectName(_fromUtf8("transcript_proj"))
        self.horizontalLayout_10.addWidget(self.transcript_proj)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_8 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_8.setMinimumSize(QtCore.QSize(80, 0))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_11.addWidget(self.label_8)
        self.combo_proj = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.combo_proj.setObjectName(_fromUtf8("combo_proj"))
        self.horizontalLayout_11.addWidget(self.combo_proj)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.checkDisplay = QtGui.QPushButton(Dialog)
        self.checkDisplay.setGeometry(QtCore.QRect(930, 330, 131, 51))
        self.checkDisplay.setObjectName(_fromUtf8("checkDisplay"))
        self.reportBtn = QtGui.QPushButton(Dialog)
        self.reportBtn.setGeometry(QtCore.QRect(930, 390, 131, 51))
        self.reportBtn.setObjectName(_fromUtf8("reportBtn"))
        self.textEdit = QtGui.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(940, 460, 104, 78))
        self.textEdit.setObjectName(_fromUtf8("textEdit"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Main", None))
        self.label.setText(_translate("Dialog", "Secret Key", None))
        self.label_2.setText(_translate("Dialog", "Public Key ", None))
        self.label_3.setText(_translate("Dialog", "    http:     ", None))
        self.startBtn.setText(_translate("Dialog", "Start Test", None))
        self.pushButton_2.setText(_translate("Dialog", "Quit", None))
        self.fileLoad.setText(_translate("Dialog", "Load Test File", None))
        self.loadTxtBtn.setText(_translate("Dialog", "Load Text Files", None))
        self.loadFileBtn.setText(_translate("Dialog", "Load Files", None))
        self.label_4.setText(_translate("Dialog", "Regular Project", None))
        self.label_5.setText(_translate("Dialog", "Expert Project", None))
        self.label_6.setText(_translate("Dialog", "Proofreading", None))
        self.label_7.setText(_translate("Dialog", "Transcription", None))
        self.label_8.setText(_translate("Dialog", "Combo Project", None))
        self.checkDisplay.setText(_translate("Dialog", "Whole check display", None))
        self.reportBtn.setText(_translate("Dialog", "See Report", None))

