# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_line_design.ui'
#
# Created: Tue Jul  5 22:49:05 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_NewLine(object):
    def setupUi(self, NewLine):
        NewLine.setObjectName(_fromUtf8("NewLine"))
        NewLine.resize(850, 740)
        NewLine.setMinimumSize(QtCore.QSize(850, 740))
        NewLine.setMaximumSize(QtCore.QSize(850, 740))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("logo.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        NewLine.setWindowIcon(icon)
        NewLine.setStyleSheet(_fromUtf8("background: rgb(128,128, 128)"))
        self.verticalLayoutWidget = QtGui.QWidget(NewLine)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 831, 721))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_49 = QtGui.QHBoxLayout()
        self.horizontalLayout_49.setObjectName(_fromUtf8("horizontalLayout_49"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.verticalLayoutWidget)
        self.label.setMinimumSize(QtCore.QSize(150, 30))
        self.label.setMaximumSize(QtCore.QSize(150, 30))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.newMethod = QtGui.QComboBox(self.verticalLayoutWidget)
        self.newMethod.setMinimumSize(QtCore.QSize(350, 30))
        self.newMethod.setMaximumSize(QtCore.QSize(350, 30))
        self.newMethod.setStyleSheet(_fromUtf8("background:rgb(204,204,204);"))
        self.newMethod.setObjectName(_fromUtf8("newMethod"))
        self.horizontalLayout.addWidget(self.newMethod)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_2.setMinimumSize(QtCore.QSize(50, 30))
        self.label_2.setMaximumSize(QtCore.QSize(50, 30))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.newAddress = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.newAddress.setMinimumSize(QtCore.QSize(450, 30))
        self.newAddress.setMaximumSize(QtCore.QSize(450, 30))
        self.newAddress.setStyleSheet(_fromUtf8("background:rgb(204,204,204);\n"
"border: 1px solid black;\n"
"border-radius: 5px;"))
        self.newAddress.setObjectName(_fromUtf8("newAddress"))
        self.horizontalLayout_2.addWidget(self.newAddress)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_3.setMinimumSize(QtCore.QSize(50, 30))
        self.label_3.setMaximumSize(QtCore.QSize(50, 30))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.newTitle = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.newTitle.setMinimumSize(QtCore.QSize(450, 30))
        self.newTitle.setMaximumSize(QtCore.QSize(450, 30))
        self.newTitle.setStyleSheet(_fromUtf8("background:rgb(204,204,204);\n"
"border: 1px solid black;\n"
"border-radius: 5px;"))
        self.newTitle.setObjectName(_fromUtf8("newTitle"))
        self.horizontalLayout_3.addWidget(self.newTitle)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_41 = QtGui.QHBoxLayout()
        self.horizontalLayout_41.setObjectName(_fromUtf8("horizontalLayout_41"))
        self.saveForNext = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.saveForNext.setMinimumSize(QtCore.QSize(507, 20))
        self.saveForNext.setMaximumSize(QtCore.QSize(507, 20))
        self.saveForNext.setObjectName(_fromUtf8("saveForNext"))
        self.horizontalLayout_41.addWidget(self.saveForNext)
        self.verticalLayout_4.addLayout(self.horizontalLayout_41)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_30 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_30.setMinimumSize(QtCore.QSize(0, 20))
        self.label_30.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_30.setWordWrap(False)
        self.label_30.setMargin(0)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.verticalLayout_3.addWidget(self.label_30)
        self.horizontalLayout_30 = QtGui.QHBoxLayout()
        self.horizontalLayout_30.setObjectName(_fromUtf8("horizontalLayout_30"))
        self.horizontalLayout_31 = QtGui.QHBoxLayout()
        self.horizontalLayout_31.setObjectName(_fromUtf8("horizontalLayout_31"))
        self.checkPrevValue_1 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.checkPrevValue_1.setMinimumSize(QtCore.QSize(20, 20))
        self.checkPrevValue_1.setMaximumSize(QtCore.QSize(20, 20))
        self.checkPrevValue_1.setText(_fromUtf8(""))
        self.checkPrevValue_1.setObjectName(_fromUtf8("checkPrevValue_1"))
        self.horizontalLayout_31.addWidget(self.checkPrevValue_1)
        self.label_24 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_24.setMinimumSize(QtCore.QSize(40, 20))
        self.label_24.setMaximumSize(QtCore.QSize(40, 20))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_31.addWidget(self.label_24)
        self.check_one_name = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.check_one_name.setMinimumSize(QtCore.QSize(150, 20))
        self.check_one_name.setMaximumSize(QtCore.QSize(150, 20))
        self.check_one_name.setStyleSheet(_fromUtf8("background:rgb(204,204,204);\n"
"border: 1px solid black;\n"
"border-radius: 5px;"))
        self.check_one_name.setObjectName(_fromUtf8("check_one_name"))
        self.horizontalLayout_31.addWidget(self.check_one_name)
        self.horizontalLayout_30.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_32 = QtGui.QHBoxLayout()
        self.horizontalLayout_32.setObjectName(_fromUtf8("horizontalLayout_32"))
        self.label_25 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_25.setMinimumSize(QtCore.QSize(40, 20))
        self.label_25.setMaximumSize(QtCore.QSize(40, 20))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout_32.addWidget(self.label_25)
        self.check_one_value = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.check_one_value.setMinimumSize(QtCore.QSize(222, 20))
        self.check_one_value.setMaximumSize(QtCore.QSize(222, 20))
        self.check_one_value.setStyleSheet(_fromUtf8("background:rgb(204,204,204);\n"
"border: 1px solid black;\n"
"border-radius: 5px;"))
        self.check_one_value.setObjectName(_fromUtf8("check_one_value"))
        self.horizontalLayout_32.addWidget(self.check_one_value)
        self.horizontalLayout_30.addLayout(self.horizontalLayout_32)
        self.verticalLayout_3.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_33 = QtGui.QHBoxLayout()
        self.horizontalLayout_33.setObjectName(_fromUtf8("horizontalLayout_33"))
        self.horizontalLayout_34 = QtGui.QHBoxLayout()
        self.horizontalLayout_34.setObjectName(_fromUtf8("horizontalLayout_34"))
        self.checkPrevValue_2 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.checkPrevValue_2.setMinimumSize(QtCore.QSize(20, 20))
        self.checkPrevValue_2.setMaximumSize(QtCore.QSize(20, 20))
        self.checkPrevValue_2.setText(_fromUtf8(""))
        self.checkPrevValue_2.setObjectName(_fromUtf8("checkPrevValue_2"))
        self.horizontalLayout_34.addWidget(self.checkPrevValue_2)
        self.label_26 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_26.setMinimumSize(QtCore.QSize(40, 20))
        self.label_26.setMaximumSize(QtCore.QSize(40, 20))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_34.addWidget(self.label_26)
        self.check_two_name = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.check_two_name.setMinimumSize(QtCore.QSize(150, 20))
        self.check_two_name.setMaximumSize(QtCore.QSize(150, 20))
        self.check_two_name.setStyleSheet(_fromUtf8("background:rgb(204,204,204);\n"
"border: 1px solid black;\n"
"border-radius: 5px;"))
        self.check_two_name.setObjectName(_fromUtf8("check_two_name"))
        self.horizontalLayout_34.addWidget(self.check_two_name)
        self.horizontalLayout_33.addLayout(self.horizontalLayout_34)
        self.horizontalLayout_35 = QtGui.QHBoxLayout()
        self.horizontalLayout_35.setObjectName(_fromUtf8("horizontalLayout_35"))
        self.label_27 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_27.setMinimumSize(QtCore.QSize(40, 20))
        self.label_27.setMaximumSize(QtCore.QSize(40, 20))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.horizontalLayout_35.addWidget(self.label_27)
        self.check_two_value = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.check_two_value.setMinimumSize(QtCore.QSize(222, 20))
        self.check_two_value.setMaximumSize(QtCore.QSize(222, 20))
        self.check_two_value.setStyleSheet(_fromUtf8("background:rgb(204,204,204);\n"
"border: 1px solid black;\n"
"border-radius: 5px;"))
        self.check_two_value.setObjectName(_fromUtf8("check_two_value"))
        self.horizontalLayout_35.addWidget(self.check_two_value)
        self.horizontalLayout_33.addLayout(self.horizontalLayout_35)
        self.verticalLayout_3.addLayout(self.horizontalLayout_33)
        self.horizontalLayout_36 = QtGui.QHBoxLayout()
        self.horizontalLayout_36.setObjectName(_fromUtf8("horizontalLayout_36"))
        self.horizontalLayout_37 = QtGui.QHBoxLayout()
        self.horizontalLayout_37.setObjectName(_fromUtf8("horizontalLayout_37"))
        self.checkPrevValue_3 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.checkPrevValue_3.setMinimumSize(QtCore.QSize(20, 20))
        self.checkPrevValue_3.setMaximumSize(QtCore.QSize(20, 20))
        self.checkPrevValue_3.setText(_fromUtf8(""))
        self.checkPrevValue_3.setObjectName(_fromUtf8("checkPrevValue_3"))
        self.horizontalLayout_37.addWidget(self.checkPrevValue_3)
        self.label_28 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_28.setMinimumSize(QtCore.QSize(40, 20))
        self.label_28.setMaximumSize(QtCore.QSize(40, 20))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.horizontalLayout_37.addWidget(self.label_28)
        self.check_three_name = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.check_three_name.setMinimumSize(QtCore.QSize(150, 20))
        self.check_three_name.setMaximumSize(QtCore.QSize(150, 20))
        self.check_three_name.setStyleSheet(_fromUtf8("background:rgb(204,204,204);\n"
"border: 1px solid black;\n"
"border-radius: 5px;"))
        self.check_three_name.setObjectName(_fromUtf8("check_three_name"))
        self.horizontalLayout_37.addWidget(self.check_three_name)
        self.horizontalLayout_36.addLayout(self.horizontalLayout_37)
        self.horizontalLayout_38 = QtGui.QHBoxLayout()
        self.horizontalLayout_38.setObjectName(_fromUtf8("horizontalLayout_38"))
        self.label_29 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_29.setMinimumSize(QtCore.QSize(40, 20))
        self.label_29.setMaximumSize(QtCore.QSize(40, 20))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.horizontalLayout_38.addWidget(self.label_29)
        self.check_three_value = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.check_three_value.setMinimumSize(QtCore.QSize(222, 20))
        self.check_three_value.setMaximumSize(QtCore.QSize(222, 20))
        self.check_three_value.setStyleSheet(_fromUtf8("background:rgb(204,204,204);\n"
"border: 1px solid black;\n"
"border-radius: 5px;"))
        self.check_three_value.setObjectName(_fromUtf8("check_three_value"))
        self.horizontalLayout_38.addWidget(self.check_three_value)
        self.horizontalLayout_36.addLayout(self.horizontalLayout_38)
        self.verticalLayout_3.addLayout(self.horizontalLayout_36)
        self.horizontalLayout_39 = QtGui.QHBoxLayout()
        self.horizontalLayout_39.setObjectName(_fromUtf8("horizontalLayout_39"))
        self.horizontalLayout_40 = QtGui.QHBoxLayout()
        self.horizontalLayout_40.setObjectName(_fromUtf8("horizontalLayout_40"))
        self.checkPrevValue_4 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.checkPrevValue_4.setMinimumSize(QtCore.QSize(20, 20))
        self.checkPrevValue_4.setMaximumSize(QtCore.QSize(20, 20))
        self.checkPrevValue_4.setText(_fromUtf8(""))
        self.checkPrevValue_4.setObjectName(_fromUtf8("checkPrevValue_4"))
        self.horizontalLayout_40.addWidget(self.checkPrevValue_4)
        self.label_31 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_31.setMinimumSize(QtCore.QSize(40, 20))
        self.label_31.setMaximumSize(QtCore.QSize(40, 20))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.horizontalLayout_40.addWidget(self.label_31)
        self.check_four_name = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.check_four_name.setMinimumSize(QtCore.QSize(150, 20))
        self.check_four_name.setMaximumSize(QtCore.QSize(150, 20))
        self.check_four_name.setStyleSheet(_fromUtf8("background:rgb(204,204,204);\n"
"border: 1px solid black;\n"
"border-radius: 5px;"))
        self.check_four_name.setObjectName(_fromUtf8("check_four_name"))
        self.horizontalLayout_40.addWidget(self.check_four_name)
        self.horizontalLayout_39.addLayout(self.horizontalLayout_40)
        self.horizontalLayout_42 = QtGui.QHBoxLayout()
        self.horizontalLayout_42.setObjectName(_fromUtf8("horizontalLayout_42"))
        self.label_32 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_32.setMinimumSize(QtCore.QSize(40, 20))
        self.label_32.setMaximumSize(QtCore.QSize(40, 20))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.horizontalLayout_42.addWidget(self.label_32)
        self.check_four_value = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.check_four_value.setMinimumSize(QtCore.QSize(222, 20))
        self.check_four_value.setMaximumSize(QtCore.QSize(222, 20))
        self.check_four_value.setStyleSheet(_fromUtf8("background:rgb(204,204,204);\n"
"border: 1px solid black;\n"
"border-radius: 5px;"))
        self.check_four_value.setObjectName(_fromUtf8("check_four_value"))
        self.horizontalLayout_42.addWidget(self.check_four_value)
        self.horizontalLayout_39.addLayout(self.horizontalLayout_42)
        self.verticalLayout_3.addLayout(self.horizontalLayout_39)
        self.horizontalLayout_43 = QtGui.QHBoxLayout()
        self.horizontalLayout_43.setObjectName(_fromUtf8("horizontalLayout_43"))
        self.horizontalLayout_44 = QtGui.QHBoxLayout()
        self.horizontalLayout_44.setObjectName(_fromUtf8("horizontalLayout_44"))
        self.checkPrevValue_5 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.checkPrevValue_5.setMinimumSize(QtCore.QSize(20, 20))
        self.checkPrevValue_5.setMaximumSize(QtCore.QSize(20, 20))
        self.checkPrevValue_5.setText(_fromUtf8(""))
        self.checkPrevValue_5.setObjectName(_fromUtf8("checkPrevValue_5"))
        self.horizontalLayout_44.addWidget(self.checkPrevValue_5)
        self.label_33 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_33.setMinimumSize(QtCore.QSize(40, 20))
        self.label_33.setMaximumSize(QtCore.QSize(40, 20))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.horizontalLayout_44.addWidget(self.label_33)
        self.check_five_name = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.check_five_name.setMinimumSize(QtCore.QSize(150, 20))
        self.check_five_name.setMaximumSize(QtCore.QSize(150, 20))
        self.check_five_name.setStyleSheet(_fromUtf8("background:rgb(204,204,204);\n"
"border: 1px solid black;\n"
"border-radius: 5px;"))
        self.check_five_name.setObjectName(_fromUtf8("check_five_name"))
        self.horizontalLayout_44.addWidget(self.check_five_name)
        self.horizontalLayout_43.addLayout(self.horizontalLayout_44)
        self.horizontalLayout_45 = QtGui.QHBoxLayout()
        self.horizontalLayout_45.setObjectName(_fromUtf8("horizontalLayout_45"))
        self.label_34 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_34.setMinimumSize(QtCore.QSize(40, 20))
        self.label_34.setMaximumSize(QtCore.QSize(40, 20))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.horizontalLayout_45.addWidget(self.label_34)
        self.check_five_value = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.check_five_value.setMinimumSize(QtCore.QSize(222, 20))
        self.check_five_value.setMaximumSize(QtCore.QSize(222, 20))
        self.check_five_value.setStyleSheet(_fromUtf8("background:rgb(204,204,204);\n"
"border: 1px solid black;\n"
"border-radius: 5px;"))
        self.check_five_value.setObjectName(_fromUtf8("check_five_value"))
        self.horizontalLayout_45.addWidget(self.check_five_value)
        self.horizontalLayout_43.addLayout(self.horizontalLayout_45)
        self.verticalLayout_3.addLayout(self.horizontalLayout_43)
        self.horizontalLayout_46 = QtGui.QHBoxLayout()
        self.horizontalLayout_46.setObjectName(_fromUtf8("horizontalLayout_46"))
        self.horizontalLayout_47 = QtGui.QHBoxLayout()
        self.horizontalLayout_47.setObjectName(_fromUtf8("horizontalLayout_47"))
        self.checkPrevValue_6 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.checkPrevValue_6.setMinimumSize(QtCore.QSize(20, 20))
        self.checkPrevValue_6.setMaximumSize(QtCore.QSize(20, 20))
        self.checkPrevValue_6.setText(_fromUtf8(""))
        self.checkPrevValue_6.setObjectName(_fromUtf8("checkPrevValue_6"))
        self.horizontalLayout_47.addWidget(self.checkPrevValue_6)
        self.label_35 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_35.setMinimumSize(QtCore.QSize(40, 20))
        self.label_35.setMaximumSize(QtCore.QSize(40, 20))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.horizontalLayout_47.addWidget(self.label_35)
        self.check_six_name = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.check_six_name.setMinimumSize(QtCore.QSize(150, 20))
        self.check_six_name.setMaximumSize(QtCore.QSize(150, 20))
        self.check_six_name.setStyleSheet(_fromUtf8("background:rgb(204,204,204);\n"
"border: 1px solid black;\n"
"border-radius: 5px;"))
        self.check_six_name.setObjectName(_fromUtf8("check_six_name"))
        self.horizontalLayout_47.addWidget(self.check_six_name)
        self.horizontalLayout_46.addLayout(self.horizontalLayout_47)
        self.horizontalLayout_48 = QtGui.QHBoxLayout()
        self.horizontalLayout_48.setObjectName(_fromUtf8("horizontalLayout_48"))
        self.label_36 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_36.setMinimumSize(QtCore.QSize(40, 20))
        self.label_36.setMaximumSize(QtCore.QSize(40, 20))
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.horizontalLayout_48.addWidget(self.label_36)
        self.check_six_value = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.check_six_value.setMinimumSize(QtCore.QSize(222, 20))
        self.check_six_value.setMaximumSize(QtCore.QSize(222, 20))
        self.check_six_value.setStyleSheet(_fromUtf8("background:rgb(204,204,204);\n"
"border: 1px solid black;\n"
"border-radius: 5px;"))
        self.check_six_value.setObjectName(_fromUtf8("check_six_value"))
        self.horizontalLayout_48.addWidget(self.check_six_value)
        self.horizontalLayout_46.addLayout(self.horizontalLayout_48)
        self.verticalLayout_3.addLayout(self.horizontalLayout_46)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_23 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_23.setMinimumSize(QtCore.QSize(507, 20))
        self.label_23.setMaximumSize(QtCore.QSize(507, 20))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.verticalLayout_2.addWidget(self.label_23)
        self.findOne = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.findOne.setMinimumSize(QtCore.QSize(507, 20))
        self.findOne.setMaximumSize(QtCore.QSize(507, 20))
        self.findOne.setStyleSheet(_fromUtf8("background:rgb(204,204,204);\n"
"border: 1px solid black;\n"
"border-radius: 5px;"))
        self.findOne.setObjectName(_fromUtf8("findOne"))
        self.verticalLayout_2.addWidget(self.findOne)
        self.findTwo = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.findTwo.setMinimumSize(QtCore.QSize(507, 20))
        self.findTwo.setMaximumSize(QtCore.QSize(507, 20))
        self.findTwo.setStyleSheet(_fromUtf8("background:rgb(204,204,204);\n"
"border: 1px solid black;\n"
"border-radius: 5px;"))
        self.findTwo.setObjectName(_fromUtf8("findTwo"))
        self.verticalLayout_2.addWidget(self.findTwo)
        self.findThree = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.findThree.setMinimumSize(QtCore.QSize(507, 20))
        self.findThree.setMaximumSize(QtCore.QSize(507, 20))
        self.findThree.setStyleSheet(_fromUtf8("background:rgb(204,204,204);\n"
"border: 1px solid black;\n"
"border-radius: 5px;"))
        self.findThree.setObjectName(_fromUtf8("findThree"))
        self.verticalLayout_2.addWidget(self.findThree)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.horizontalLayout_49.addLayout(self.verticalLayout_4)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_22 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_22.setMinimumSize(QtCore.QSize(300, 20))
        self.label_22.setMaximumSize(QtCore.QSize(300, 20))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.verticalLayout.addWidget(self.label_22)
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.label_20 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_20.setMinimumSize(QtCore.QSize(60, 20))
        self.label_20.setMaximumSize(QtCore.QSize(60, 20))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_28.addWidget(self.label_20)
        self.boxS_K = QtGui.QComboBox(self.verticalLayoutWidget)
        self.boxS_K.setMinimumSize(QtCore.QSize(230, 20))
        self.boxS_K.setMaximumSize(QtCore.QSize(230, 20))
        self.boxS_K.setStyleSheet(_fromUtf8("background:rgb(204,204,204);"))
        self.boxS_K.setObjectName(_fromUtf8("boxS_K"))
        self.horizontalLayout_28.addWidget(self.boxS_K)
        self.verticalLayout.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_29 = QtGui.QHBoxLayout()
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        self.label_21 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_21.setMinimumSize(QtCore.QSize(60, 20))
        self.label_21.setMaximumSize(QtCore.QSize(60, 20))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_29.addWidget(self.label_21)
        self.boxP_K = QtGui.QComboBox(self.verticalLayoutWidget)
        self.boxP_K.setMinimumSize(QtCore.QSize(230, 20))
        self.boxP_K.setMaximumSize(QtCore.QSize(230, 20))
        self.boxP_K.setStyleSheet(_fromUtf8("background:rgb(204,204,204);"))
        self.boxP_K.setObjectName(_fromUtf8("boxP_K"))
        self.horizontalLayout_29.addWidget(self.boxP_K)
        self.verticalLayout.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_4 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_4.setMinimumSize(QtCore.QSize(40, 20))
        self.label_4.setMaximumSize(QtCore.QSize(40, 20))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_4.addWidget(self.label_4)
        self.p_one_name = QtGui.QComboBox(self.verticalLayoutWidget)
        self.p_one_name.setMinimumSize(QtCore.QSize(100, 20))
        self.p_one_name.setMaximumSize(QtCore.QSize(100, 20))
        self.p_one_name.setStyleSheet(_fromUtf8("background:rgb(204,204,204);"))
        self.p_one_name.setObjectName(_fromUtf8("p_one_name"))
        self.horizontalLayout_4.addWidget(self.p_one_name)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_5 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_5.setMinimumSize(QtCore.QSize(40, 20))
        self.label_5.setMaximumSize(QtCore.QSize(40, 20))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_5.addWidget(self.label_5)
        self.p_one_value = QtGui.QComboBox(self.verticalLayoutWidget)
        self.p_one_value.setMinimumSize(QtCore.QSize(100, 20))
        self.p_one_value.setMaximumSize(QtCore.QSize(100, 20))
        self.p_one_value.setStyleSheet(_fromUtf8("background:rgb(204,204,204);"))
        self.p_one_value.setObjectName(_fromUtf8("p_one_value"))
        self.horizontalLayout_5.addWidget(self.p_one_value)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_6 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_6.setMinimumSize(QtCore.QSize(40, 20))
        self.label_6.setMaximumSize(QtCore.QSize(40, 20))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_8.addWidget(self.label_6)
        self.p_two_name = QtGui.QComboBox(self.verticalLayoutWidget)
        self.p_two_name.setMinimumSize(QtCore.QSize(100, 20))
        self.p_two_name.setMaximumSize(QtCore.QSize(100, 20))
        self.p_two_name.setStyleSheet(_fromUtf8("background:rgb(204,204,204);"))
        self.p_two_name.setObjectName(_fromUtf8("p_two_name"))
        self.horizontalLayout_8.addWidget(self.p_two_name)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_7 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_7.setMinimumSize(QtCore.QSize(40, 20))
        self.label_7.setMaximumSize(QtCore.QSize(40, 20))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_9.addWidget(self.label_7)
        self.p_two_value = QtGui.QComboBox(self.verticalLayoutWidget)
        self.p_two_value.setMinimumSize(QtCore.QSize(100, 20))
        self.p_two_value.setMaximumSize(QtCore.QSize(100, 20))
        self.p_two_value.setStyleSheet(_fromUtf8("background:rgb(204,204,204);"))
        self.p_two_value.setObjectName(_fromUtf8("p_two_value"))
        self.horizontalLayout_9.addWidget(self.p_two_value)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_9)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_8 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_8.setMinimumSize(QtCore.QSize(40, 20))
        self.label_8.setMaximumSize(QtCore.QSize(40, 20))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_11.addWidget(self.label_8)
        self.p_three_name = QtGui.QComboBox(self.verticalLayoutWidget)
        self.p_three_name.setMinimumSize(QtCore.QSize(100, 20))
        self.p_three_name.setMaximumSize(QtCore.QSize(100, 20))
        self.p_three_name.setStyleSheet(_fromUtf8("background:rgb(204,204,204);"))
        self.p_three_name.setObjectName(_fromUtf8("p_three_name"))
        self.horizontalLayout_11.addWidget(self.p_three_name)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_9 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_9.setMinimumSize(QtCore.QSize(40, 20))
        self.label_9.setMaximumSize(QtCore.QSize(40, 20))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_12.addWidget(self.label_9)
        self.p_three_value = QtGui.QComboBox(self.verticalLayoutWidget)
        self.p_three_value.setMinimumSize(QtCore.QSize(100, 20))
        self.p_three_value.setMaximumSize(QtCore.QSize(100, 20))
        self.p_three_value.setStyleSheet(_fromUtf8("background:rgb(204,204,204);"))
        self.p_three_value.setObjectName(_fromUtf8("p_three_value"))
        self.horizontalLayout_12.addWidget(self.p_three_value)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_12)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.label_14 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_14.setMinimumSize(QtCore.QSize(40, 20))
        self.label_14.setMaximumSize(QtCore.QSize(40, 20))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_20.addWidget(self.label_14)
        self.p_four_name = QtGui.QComboBox(self.verticalLayoutWidget)
        self.p_four_name.setMinimumSize(QtCore.QSize(100, 20))
        self.p_four_name.setMaximumSize(QtCore.QSize(100, 20))
        self.p_four_name.setStyleSheet(_fromUtf8("background:rgb(204,204,204);"))
        self.p_four_name.setObjectName(_fromUtf8("p_four_name"))
        self.horizontalLayout_20.addWidget(self.p_four_name)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.label_15 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_15.setMinimumSize(QtCore.QSize(40, 20))
        self.label_15.setMaximumSize(QtCore.QSize(40, 20))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_21.addWidget(self.label_15)
        self.p_four_value = QtGui.QComboBox(self.verticalLayoutWidget)
        self.p_four_value.setMinimumSize(QtCore.QSize(100, 20))
        self.p_four_value.setMaximumSize(QtCore.QSize(100, 20))
        self.p_four_value.setStyleSheet(_fromUtf8("background:rgb(204,204,204);"))
        self.p_four_value.setObjectName(_fromUtf8("p_four_value"))
        self.horizontalLayout_21.addWidget(self.p_four_value)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_21)
        self.verticalLayout.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_10 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_10.setMinimumSize(QtCore.QSize(40, 20))
        self.label_10.setMaximumSize(QtCore.QSize(40, 20))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_14.addWidget(self.label_10)
        self.p_five_name = QtGui.QComboBox(self.verticalLayoutWidget)
        self.p_five_name.setMinimumSize(QtCore.QSize(100, 20))
        self.p_five_name.setMaximumSize(QtCore.QSize(100, 20))
        self.p_five_name.setStyleSheet(_fromUtf8("background:rgb(204,204,204);"))
        self.p_five_name.setObjectName(_fromUtf8("p_five_name"))
        self.horizontalLayout_14.addWidget(self.p_five_name)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_11 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_11.setMinimumSize(QtCore.QSize(40, 20))
        self.label_11.setMaximumSize(QtCore.QSize(40, 20))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_15.addWidget(self.label_11)
        self.p_five_value = QtGui.QComboBox(self.verticalLayoutWidget)
        self.p_five_value.setMinimumSize(QtCore.QSize(100, 20))
        self.p_five_value.setMaximumSize(QtCore.QSize(100, 20))
        self.p_five_value.setStyleSheet(_fromUtf8("background:rgb(204,204,204);"))
        self.p_five_value.setObjectName(_fromUtf8("p_five_value"))
        self.horizontalLayout_15.addWidget(self.p_five_value)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_15)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.label_12 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_12.setMinimumSize(QtCore.QSize(40, 20))
        self.label_12.setMaximumSize(QtCore.QSize(40, 20))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_17.addWidget(self.label_12)
        self.p_six_name = QtGui.QComboBox(self.verticalLayoutWidget)
        self.p_six_name.setMinimumSize(QtCore.QSize(100, 20))
        self.p_six_name.setMaximumSize(QtCore.QSize(100, 20))
        self.p_six_name.setStyleSheet(_fromUtf8("background:rgb(204,204,204);"))
        self.p_six_name.setObjectName(_fromUtf8("p_six_name"))
        self.horizontalLayout_17.addWidget(self.p_six_name)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.label_13 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_13.setMinimumSize(QtCore.QSize(40, 20))
        self.label_13.setMaximumSize(QtCore.QSize(40, 20))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_18.addWidget(self.label_13)
        self.p_six_value = QtGui.QComboBox(self.verticalLayoutWidget)
        self.p_six_value.setMinimumSize(QtCore.QSize(100, 20))
        self.p_six_value.setMaximumSize(QtCore.QSize(100, 20))
        self.p_six_value.setStyleSheet(_fromUtf8("background:rgb(204,204,204);"))
        self.p_six_value.setObjectName(_fromUtf8("p_six_value"))
        self.horizontalLayout_18.addWidget(self.p_six_value)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_18)
        self.verticalLayout.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.label_18 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_18.setMinimumSize(QtCore.QSize(40, 20))
        self.label_18.setMaximumSize(QtCore.QSize(40, 20))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_26.addWidget(self.label_18)
        self.p_seven_name = QtGui.QComboBox(self.verticalLayoutWidget)
        self.p_seven_name.setMinimumSize(QtCore.QSize(100, 20))
        self.p_seven_name.setMaximumSize(QtCore.QSize(100, 20))
        self.p_seven_name.setStyleSheet(_fromUtf8("background:rgb(204,204,204);"))
        self.p_seven_name.setObjectName(_fromUtf8("p_seven_name"))
        self.horizontalLayout_26.addWidget(self.p_seven_name)
        self.horizontalLayout_25.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.label_19 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_19.setMinimumSize(QtCore.QSize(40, 20))
        self.label_19.setMaximumSize(QtCore.QSize(40, 20))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_27.addWidget(self.label_19)
        self.p_seven_value = QtGui.QComboBox(self.verticalLayoutWidget)
        self.p_seven_value.setMinimumSize(QtCore.QSize(100, 20))
        self.p_seven_value.setMaximumSize(QtCore.QSize(100, 20))
        self.p_seven_value.setStyleSheet(_fromUtf8("background:rgb(204,204,204);"))
        self.p_seven_value.setObjectName(_fromUtf8("p_seven_value"))
        self.horizontalLayout_27.addWidget(self.p_seven_value)
        self.horizontalLayout_25.addLayout(self.horizontalLayout_27)
        self.verticalLayout.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.label_16 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_16.setMinimumSize(QtCore.QSize(40, 20))
        self.label_16.setMaximumSize(QtCore.QSize(40, 20))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_23.addWidget(self.label_16)
        self.p_eight_name = QtGui.QComboBox(self.verticalLayoutWidget)
        self.p_eight_name.setMinimumSize(QtCore.QSize(100, 20))
        self.p_eight_name.setMaximumSize(QtCore.QSize(100, 20))
        self.p_eight_name.setStyleSheet(_fromUtf8("background:rgb(204,204,204);"))
        self.p_eight_name.setObjectName(_fromUtf8("p_eight_name"))
        self.horizontalLayout_23.addWidget(self.p_eight_name)
        self.horizontalLayout_22.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.label_17 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_17.setMinimumSize(QtCore.QSize(40, 20))
        self.label_17.setMaximumSize(QtCore.QSize(40, 20))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_24.addWidget(self.label_17)
        self.p_eight_value = QtGui.QComboBox(self.verticalLayoutWidget)
        self.p_eight_value.setMinimumSize(QtCore.QSize(100, 20))
        self.p_eight_value.setMaximumSize(QtCore.QSize(100, 20))
        self.p_eight_value.setStyleSheet(_fromUtf8("background:rgb(204,204,204);"))
        self.p_eight_value.setObjectName(_fromUtf8("p_eight_value"))
        self.horizontalLayout_24.addWidget(self.p_eight_value)
        self.horizontalLayout_22.addLayout(self.horizontalLayout_24)
        self.verticalLayout.addLayout(self.horizontalLayout_22)
        self.paramTextEdit = QtGui.QTextEdit(self.verticalLayoutWidget)
        self.paramTextEdit.setMinimumSize(QtCore.QSize(304, 128))
        self.paramTextEdit.setMaximumSize(QtCore.QSize(304, 128))
        self.paramTextEdit.setStyleSheet(_fromUtf8("background:rgb(204,204,204);\n"
"border: 1px solid black;\n"
"border-radius: 5px;"))
        self.paramTextEdit.setObjectName(_fromUtf8("paramTextEdit"))
        self.verticalLayout.addWidget(self.paramTextEdit)
        self.horizontalLayout_49.addLayout(self.verticalLayout)
        self.verticalLayout_5.addLayout(self.horizontalLayout_49)
        self.horizontalLayout_50 = QtGui.QHBoxLayout()
        self.horizontalLayout_50.setObjectName(_fromUtf8("horizontalLayout_50"))
        self.testLineBtn = QtGui.QPushButton(self.verticalLayoutWidget)
        self.testLineBtn.setMinimumSize(QtCore.QSize(150, 40))
        self.testLineBtn.setMaximumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.testLineBtn.setFont(font)
        self.testLineBtn.setStyleSheet(_fromUtf8("background:rgb(80,80,80);\n"
"color: rgb(204,204,204);"))
        self.testLineBtn.setObjectName(_fromUtf8("testLineBtn"))
        self.horizontalLayout_50.addWidget(self.testLineBtn)
        self.saveMain = QtGui.QPushButton(self.verticalLayoutWidget)
        self.saveMain.setMinimumSize(QtCore.QSize(150, 40))
        self.saveMain.setMaximumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.saveMain.setFont(font)
        self.saveMain.setStyleSheet(_fromUtf8("background:rgb(80,80,80);\n"
"color: rgb(204,204,204);"))
        self.saveMain.setObjectName(_fromUtf8("saveMain"))
        self.horizontalLayout_50.addWidget(self.saveMain)
        self.closeBtn = QtGui.QPushButton(self.verticalLayoutWidget)
        self.closeBtn.setMinimumSize(QtCore.QSize(150, 40))
        self.closeBtn.setMaximumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.closeBtn.setFont(font)
        self.closeBtn.setStyleSheet(_fromUtf8("background:rgb(80,80,80);\n"
"color: rgb(204,204,204);"))
        self.closeBtn.setObjectName(_fromUtf8("closeBtn"))
        self.horizontalLayout_50.addWidget(self.closeBtn)
        self.verticalLayout_5.addLayout(self.horizontalLayout_50)
        self.label_37 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_37.setMinimumSize(QtCore.QSize(829, 220))
        self.label_37.setMaximumSize(QtCore.QSize(829, 220))
        self.label_37.setStyleSheet(_fromUtf8("background:rgb(221, 255, 204);\n"
"border: 1px solid black;\n"
"border-radius: 5px;"))
        self.label_37.setWordWrap(True)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.verticalLayout_5.addWidget(self.label_37)

        self.retranslateUi(NewLine)
        QtCore.QMetaObject.connectSlotsByName(NewLine)

    def retranslateUi(self, NewLine):
        NewLine.setWindowTitle(_translate("NewLine", "API Test - New Line", None))
        self.label.setText(_translate("NewLine", "Method <GET/POST>:", None))
        self.label_2.setText(_translate("NewLine", "Address:", None))
        self.label_3.setText(_translate("NewLine", "Title:", None))
        self.saveForNext.setText(_translate("NewLine", "Save response for next check", None))
        self.label_30.setText(_translate("NewLine", "                                                                            Check:", None))
        self.label_24.setText(_translate("NewLine", "Name:", None))
        self.label_25.setText(_translate("NewLine", "Value:", None))
        self.label_26.setText(_translate("NewLine", "Name:", None))
        self.label_27.setText(_translate("NewLine", "Value:", None))
        self.label_28.setText(_translate("NewLine", "Name:", None))
        self.label_29.setText(_translate("NewLine", "Value:", None))
        self.label_31.setText(_translate("NewLine", "Name:", None))
        self.label_32.setText(_translate("NewLine", "Value:", None))
        self.label_33.setText(_translate("NewLine", "Name:", None))
        self.label_34.setText(_translate("NewLine", "Value:", None))
        self.label_35.setText(_translate("NewLine", "Name:", None))
        self.label_36.setText(_translate("NewLine", "Value:", None))
        self.label_23.setText(_translate("NewLine", "                                                                             Find:", None))
        self.label_22.setText(_translate("NewLine", "                                        Params:", None))
        self.label_20.setText(_translate("NewLine", "Secret Key:", None))
        self.label_21.setText(_translate("NewLine", "Public Key: ", None))
        self.label_4.setText(_translate("NewLine", "Name:", None))
        self.label_5.setText(_translate("NewLine", "Value:", None))
        self.label_6.setText(_translate("NewLine", "Name:", None))
        self.label_7.setText(_translate("NewLine", "Value:", None))
        self.label_8.setText(_translate("NewLine", "Name:", None))
        self.label_9.setText(_translate("NewLine", "Value:", None))
        self.label_14.setText(_translate("NewLine", "Name:", None))
        self.label_15.setText(_translate("NewLine", "Value:", None))
        self.label_10.setText(_translate("NewLine", "Name:", None))
        self.label_11.setText(_translate("NewLine", "Value:", None))
        self.label_12.setText(_translate("NewLine", "Name:", None))
        self.label_13.setText(_translate("NewLine", "Value:", None))
        self.label_18.setText(_translate("NewLine", "Name:", None))
        self.label_19.setText(_translate("NewLine", "Value:", None))
        self.label_16.setText(_translate("NewLine", "Name:", None))
        self.label_17.setText(_translate("NewLine", "Value:", None))
        self.testLineBtn.setText(_translate("NewLine", "Test Line", None))
        self.saveMain.setText(_translate("NewLine", "Save to main test", None))
        self.closeBtn.setText(_translate("NewLine", "Close", None))
        self.label_37.setText(_translate("NewLine", "<html><head/><body><p><span style=\" font-weight:600;\">Instructions for creating a new line:</span></p><p><span style=\" font-weight:600;\">1.</span> Fill all necessary fields: method, address, title, parameters. You don\'t have to fill the check and find fields on the first run, you can fill them after you try the line and see the response.</p><p><span style=\" font-weight:600;\">2.</span> Click on &quot;Test Line&quot;, this will save your new line. In order to save you have to press this button first.</p><p><span style=\" font-weight:600;\">3.</span> After the line is saved you can test your new line by going to the main window and clicking on &quot;Start Test&quot;, this will execute only the new line (don\'t close new line window, otherwise all inserted data will be lost).</p><p><span style=\" font-weight:600;\">4.</span> After you tested the line you can save it to the main test file in order for the line to be executed in the main test.</p><p><span style=\" font-weight:600;\">*</span> You can delete a line by going to the main window and clicking on &quot;Whole Check Display&quot;, find the unwanted line and click on &quot;delete selected line&quot;.</p></body></html>", None))

